### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by chrisduerr** [unicode-rs/unicode-width#15]
Looking at this repositorie's history, it seems like it is currently mostly in a passively maintained state. @kwantam has not committed anything in over a year and apparently @alexcrichton and @Manishearth have taken over with some passive maintenance patches.

Generally this wouldn't be a problem, however unicode width is not something that will work sufficiently well just by passively maintaining the project. While the code itself might not need any updates, the unicode standard is updated regularly.

For the Alacritty project which currently relies on this crate to provide up to date Rust unicode width information, this is quite important, since outdated unicode width information will lead to severe rendering artifacts in terminal emulators.

Is there any plan for regularly updating this library and getting it more actively maintained to stay up to date with the latest Unicode standard? It might even work to automatically run the script to update unicode information, however I'd be a bit cautious about that.

I'd be happy to help if the issue is with manpower, however I want to try and avoid forking this library just to regularly update the unicode table for Alacritty.

**Comment by Manishearth** [comment]
I'm committed to continue to maintain unicode-rs libraries, however I won't necessarily be able to make large changes.

More than happy to accept PRs that update to newer Unicode versions.

You definitely don't want to automatically run the update script, some unicode versions introduce spec changes and updates need to check that as well.

**Comment by Manishearth** [comment]
I should probably also add myself as a maintainer to the crate metadata to avoid confusion
