### ISSUE TITLE
impl UnicodeWidthChar for u8

### ISSUE THREAD

**Issue by nrc** [unicode-rs/unicode-width#2]
To replace the old `unicode::str::utf8_char_width`

**Comment by kwantam** [comment]
rustc_unicode::str::utf8_char_width is still there, though it's behind the `unicode` feature gate.

I don't think there are any plans to deprecate this in librustc_unicode, since it has to do with UTF-8 representation, not Unicode semantics. I'll inquire.

**Comment by nrc** [comment]
@kwantam libunicode is gone from the distro. It does look like it is the wrong kind of width though. I should look in one of the other unicode libs.

**Comment by kwantam** [comment]
libunicode is renamed librustc_unicode. The following works on the 4/20 nightly:

    #![feature(unicode)]
    
    extern crate rustc_unicode;
    
    use rustc_unicode::str as ustr;
    
    fn main() {
        for i in (0 .. 256) {
            print!("{} ", ustr::utf8_char_width(i as u8));
        }
        println!("");
    }
