### ISSUE TITLE
Is calculating 👩‍🔬 as 4-wide really UAX-11 compliant?

### ISSUE THREAD

**Issue by Artoria2e5** [unicode-rs/unicode-width#20]
The Recommendations section of UAX-11 has included this statement ever since Revision 33 from Unicode 10.0:

> [UTS51] emoji presentation sequences behave as though they were East Asian Wide, regardless of their assigned East_Asian_Width property value.

If the crate is to operate according to UAX-11 per the README, it appears that it needs to have the capability to count composed emoji sequences as a single East Asian Wide (2-width) grapheme. That would mean a `unicode-segmentation` dependency if we are looking for a fix, or a change to the README to describe this deviation if we are trying to be honest.

**Comment by Manishearth** [comment]
Yes, it is compliant, because "emoji presentation sequence" refers to a [specific thing involving a variation selector](https://www.unicode.org/reports/tr51/#def_emoji_presentation_sequence)

This case is handled by the data treating variation selectors as zero-width.

**Comment by Artoria2e5** [comment]
D'oh, *that* makes sense now.
