### ISSUE TITLE
U+FE0F emojis

### ISSUE THREAD

**Issue by truchi** [unicode-rs/unicode-width#21]
Hello !

```rust
dbg!(unicode_width::UnicodeWidthStr::width("☁️")); // 1
dbg!(unicode_width::UnicodeWidthStr::width("❤️")); // 1
dbg!(unicode_width::UnicodeWidthStr::width("☂️")); // 1
dbg!(unicode_width::UnicodeWidthStr::width("✏️")); // 1
dbg!(unicode_width::UnicodeWidthStr::width("✂️")); // 1
dbg!(unicode_width::UnicodeWidthStr::width("☎️")); // 1
dbg!(unicode_width::UnicodeWidthStr::width("✈️")); // 1
```

Is this correct?

See https://github.com/neovim/neovim/issues/7151#issuecomment-487373284.

**Comment by Manishearth** [comment]
Please see the note in the README

**Comment by truchi** [comment]
:flushed:

**Comment by truchi** [comment]
That being said, humans being like me hate reading unicode specs.
I suggest you also mention the variation selector alongside ZWJ in the readme.

Anyway, thanks for the good work.

**Comment by Manishearth** [comment]
There are many many such characters, we list a couple examples when we talk about the column width already.

**Comment by Jules-Bertholet** [comment]
#41 added support for U+FE0F. (Emoji ZWJ sequences and skintone modifiers remain unsupported, however.)
