### ISSUE TITLE
Wrong width for ❄️

### ISSUE THREAD

**Issue by imsnif** [unicode-rs/unicode-width#22]
Hey there - we've been using this library extensively for calculating widths and it's frankly been a godsend. Thank you for it.

I recently found an issue which has to do with the character: ❄️
I'm not sure how to better represent it so it won't get lost in formatting, so I'm going to try the output of this snippet:
```rust
fn main() {
    let my_chars = "❄️".chars();
    println!("{:?}", my_chars);
}
// prints: Chars(['❄', '\u{fe0f}'])
```

However, when using unicode-width, it's calculated as 1:
```rust
fn main() {
    println!("{:?}", "❄️".width());
}
// prints: 1
```

I'm far from being an expert here, I just know that this offsets our UI in Zellij in some cases. I hope I'm not barking up the wrong tree?

Thanks!

**Comment by Manishearth** [comment]
Please read the note in the README. Rendered width is font and engine dependent and is not computable from just the string.

**Comment by imsnif** [comment]
My apologies - this was a lack of understanding on my part. So just to make sure I understand (if you feel like replying): handling the `fe0f` character, which as I understand it is: https://emojipedia.org/variation-selector-16/, is something that's the responsibility of the font/rendering engine and not strictly a unicode-width thing?

**Comment by Manishearth** [comment]
Yes, we follow the Unicode spec here

**Comment by imsnif** [comment]
`0ef0` is also part of the spec, and as a newcomer to this discipline this distinction wasn't immediately clear to me. Which is why I appreciate your response.

**Comment by Manishearth** [comment]
Yes, I'm aware that variation selectors are part of the unicode spec, I'm saying that they're not handled the way you expect in the unicode width spec

**Comment by Jules-Bertholet** [comment]
https://github.com/unicode-rs/unicode-width/pull/41 added support for these variation selectors. (Emoji ZWJ sequences and skintone modifiers remain unsupported, however.)
