### ISSUE TITLE
Variation selector not taken into consideration

### ISSUE THREAD

**Issue by soywod** [unicode-rs/unicode-width#27]
I do not know enough the domain, I may be wrong. I'm using your lib to [display emails](https://github.com/soywod/himalaya), because sometime subjects contain emojis. I noticed I have some trouble to display certain emojis like 🏕 (one space is added, which breaks my table layout). When I log cell content I have sth like `cell: "Test emoji 🏕\u{fe0f}"`. I searched a bit about this `u{fe0f}` and it appears to be a [variation selector](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)). Is it sth skipped by the lib?

**Comment by Manishearth** [comment]
Please read the note in the readme:

> NOTE: The computed width values may not match the actual rendered column width. For example, the woman scientist emoji comprises of a woman emoji, a zero-width joiner and a microscope emoji.

> See [Unicode Standard Annex #11](http://www.unicode.org/reports/tr11/)[](https://github.com/unicode-rs/unicode-width#features) for precise details on what is and isn't covered by this crate.

**Comment by soywod** [comment]
Do you have any advise on how I could get the rendered width?

**Comment by Manishearth** [comment]
There is no such concept without having font information.

The assumption that each string of text has a certain width, and can even _have_ a concept of monospace, is not generalizeable to many writing systems.

**Comment by Jules-Bertholet** [comment]
#41 added support for this.
