### ISSUE TITLE
Emoji width

### ISSUE THREAD

**Issue by gwenn** [unicode-rs/unicode-width#4]
I am not sure but the displayed width of emoji seems to be at least 2:

<pre>
"❤️"
"12"
</pre>

``` rust
let w = unicode_width::UnicodeWidthStr::width("\u{2764}\u{fe0f}");
assert_eq!(2, w); // (left: `2`, right: `1`)
```

**Comment by kwantam** [comment]
The UNICODE standard defines which characters should be considered wide and which should not. To my knowledge, emoji are not considered wide characters. Note also that width refers to number of columns when displayed in monospaced font; any character can appear wider when displayed in a proportional font.

(Anecdotally, the heart symbol above occupies one column in my Unicode-aware terminal.)

**Comment by casey** [comment]
From reading [this](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1665140), I believe that as of Unicode 9, emoji are now wide characters.

I also seems that as of unicode-width 0.1.4 emojis are considered to be wide characters, so this can be closed.

PS Thanks for writing this library!

**Comment by gwenn** [comment]
[unicode-width 0.1.4](https://play.integer32.com/?gist=de568b01787fe6872086c168d4efad7e&version=undefined) returns `1`...

**Comment by casey** [comment]
Ah, it looks like unicode-width 0.1.4 reports that a `❤️` is one column wide, and a `😗` is two columns wide. I didn't specifically test the heart character, just emoji.

**Comment by ogham** [comment]
I thought I was experiencing this, but it turns out that my terminal was just getting the widths wrong and I was seeing it the wrong way!

**Comment by theindigamer** [comment]
The docs say "we provide the width in columns". For characters in X, Y, Z categories, we do A, B, C. AIUI Emoji don't really fall into those categories, so I'd naively expect the result to be whatever makes the most sense (if there is one such result). Depending on the user's system -- whether the compound emoji can be rendered properly or not (in which case, it shows up as two separate emoji) -- the computed width will be different. The crate picks the width you'd get when it shows as split up, which is a reasonable choice.

However, since there are two reasonable answers here, I think if the precise scope and limitations of the crate were made clearer, then the behavior for compound emoji wouldn't be an issue. I'm happy to open a PR to add this clarification if you agree.

**Comment by Manishearth** [comment]
> if there is one such result

There kinda isn't, the concept of "width" you're asking for is a matter of font, as well as the context (many terminals will not use emoji presentation, which means those _will_ display as two)

The crate does already mention that it follows the UTS 11 rules. Feel free to add to the readme that this may not match actual rendered column width.

**Comment by canndrew** [comment]
I'd been using this crate on the assumption that `UnicodeWidthStr::width` would give the actual displayed width in columns. It's a shame that that assumption doesn't hold :/

Is there a non-trivial subset of strings for which the displayed column width *is* exactly specified and we can rely on it being accurate for any standards-compliant terminal? If so, can we add another method to `UnicodeWidthStr` which returns an `Option<usize>`? That way my terminal GUI library can know when it might have lost track of the cursor position.

**Comment by keidax** [comment]
In regards to UAX #11, [the recommendations]( https://www.unicode.org/reports/tr11/tr11-36.html#Recommendations) state
> UTS51 emoji presentation sequences behave as though they were East Asian Wide, regardless of their assigned East_Asian_Width property value.

and as best as I can tell from [this definition](https://www.unicode.org/reports/tr51/tr51-16.html#def_emoji_presentation_sequence), `"\u{2764}\u{fe0f}"` would be a valid emoji presentation sequence.

In other words, it seems like the most "correct" behavior for a character with a text presentation by default, like U+2764, would be
``` rust
assert_eq!(1, UnicodeWidthStr::width("\u{2764}"));
assert_eq!(1, UnicodeWidthStr::width("\u{2764}\u{fe0e}"));
assert_eq!(2, UnicodeWidthStr::width("\u{2764}\u{fe0f}"));
```
And for a character with an emoji presentation by default:
``` rust
assert_eq!(2, UnicodeWidthStr::width("\u{26a1}"));
assert_eq!(1, UnicodeWidthStr::width("\u{26a1}\u{fe0e}"));
assert_eq!(2, UnicodeWidthStr::width("\u{26a1}\u{fe0f}"));
```
Of course, the rendering of this also seems to vary by OS and browser:
❤
❤︎
❤️
⚡
⚡︎
⚡️

**Comment by wez** [comment]
I don't really know much about this space, but here's my attempt at dealing with this in a terminal emulator.

```rust
/// Returns the number of cells visually occupied by a sequence
/// of graphemes
pub fn unicode_column_width(s: &str) -> usize {
    use unicode_segmentation::UnicodeSegmentation;
    s.graphemes(true).map(grapheme_column_width).sum()
}

/// Returns the number of cells visually occupied by a grapheme.
/// The input string must be a single grapheme.
pub fn grapheme_column_width(s: &str) -> usize {
    // Due to this issue:
    // https://github.com/unicode-rs/unicode-width/issues/4
    // we cannot simply use the unicode-width crate to compute
    // the desired value.
    // Let's check for emoji-ness for ourselves first
    use xi_unicode::EmojiExt;
    for c in s.chars() {
        if c.is_emoji_modifier_base() || c.is_emoji_modifier() {
            // treat modifier sequences as double wide
            return 2;
        }
    }
    UnicodeWidthStr::width(s)
}
```

**Comment by worldmind** [comment]
Not sure, but suppose that example from [this article](https://hsivonen.fi/string-length/) related to this issue:
```
fn main() {
    println!("{}", "🤦🏼‍♂️".width());
}
```
returns 5, but article author think that it must be 2

**Comment by Manishearth** [comment]
Right, this crate is dealing with a different notion of width.

**Comment by christianparpart** [comment]
@keidax is actually right. I came here not as a rust dev, but more as a VTE dev, because I actually forgot where in the huge mass of unicode (emoji) specs I was reading that emoji presentation is always considered to be east Asian wide (2 columns in mono spaced fonts).  -- so thanks for also having provided the links @keidax.

Sadly many VTEs and even client apps are still getting this wrong, but it seems to shift slightly (Kitty for example gets a lot of it right).

**Comment by Jules-Bertholet** [comment]
#41 added support for U+FE0F. (Emoji ZWJ sequences and skintone modifiers remain unsupported, however.)
