### ISSUE TITLE
Add release automation

### ISSUE THREAD

**Issue by joshka** [unicode-rs/unicode-width#57]
Consider adding some release automation that automatically creates the release notes and appends them to the github releases etc. I'm fond of the approach documented in https://github.com/joshka/github-workflows/ using Release-plz as it's simple to setup and let it run (you'd be up and running in <10 minutes with this). If you're not keen on using / forking my workflow templates, the instructions for [release-plz](https://release-plz.ieni.dev/docs/github/quickstart) are also pretty easy to follow for setting this up.

For an example from just now: all the following were all automatically generated (my entire involvement with the release was clicking merge on the PR):
- Release PR: https://github.com/joshka/bevy_ratatui/pull/4 - automatically updated after every push to main
- https://crates.io/crates/bevy_ratatui was released when I hit merge on the release PR
- Release: https://github.com/joshka/bevy_ratatui/releases/tag/v0.5.0 was added when I merged the release PR
- Changelog: https://github.com/joshka/bevy_ratatui/blob/v0.5.0/CHANGELOG.md was updated by the release PR

**Comment by Manishearth** [comment]
In general I am not in favor of autopublish workflows. Thanks for the suggestion.
