### ISSUE TITLE
Please consider providing a variant that treats grapheme clusters "incorrectly" as many terminals do

### ISSUE THREAD

**Issue by joshtriplett** [unicode-rs/unicode-width#71]
Terminals vary in their handling of grapheme clusters, such as ZWJ-based emoji clusters. See https://mitchellh.com/writing/grapheme-clusters-in-terminals for details, and https://mitchellh.com/writing/grapheme-clusters-in-terminals#terminal-comparison in particular for a table comparing terminal behavior.

Handling (for instance) ZWJ-based emoji clusters as a single emoji is the correct behavior, but many terminals do not do this. The "mode 2027" proposal mentioned in the link above would be a way for terminal applications to know and control what the terminal they're running on does with grapheme clusters. However, that proposal isn't widely supported yet.

Please consider providing a variant of the string width function, similar to `width_cjk`, which people can invoke if they know the terminal they're running on has the incorrect-but-common behavior. Short-term, terminal applications might offer configurability for this; long-term, terminals will hopefully support "mode 2027" and applications can detect/control this support to decide which width to use.

In terms of naming, perhaps something like `width_no_cluster_handling`? This doesn't particularly need to be a *short* name; applications that need to handle both cases will presumably create a wrapper that calls one or the other function at runtime, and applications should almost certainly not be hardcoding an assumption of terminals having the incorrect-but-common behavior.

**Comment by Manishearth** [comment]
I'd be rather surprised if there is a single consistent "incorrect" way of handling things common across terminals. I've seen wildly inconsistent behavior here, and typically _some_ subset of clustering is handled, though rarely emoji.

I'm not really in favor of attempting to implement something like this.

**Comment by joshtriplett** [comment]
While there are some variations in behavior, the two most common behaviors for emoji are "display each emoji separately, don't display the ZWJ" and "display the single combined emoji". Even just covering those two variations would be helpful.

**Comment by Manishearth** [comment]
@joshtriplett Not all sequences are equal. I think there's significant variation along these axes:

 - Whether or not ZWJ sequences are handled 
   - Whether or not _some_ ZWJ sequences are handled: Some terminals handle older but not newer sequences.
 - Whether or not skin tone sequences are handled (these aren't ZWJ. often how this is handled is font-dependent)
 - Whether or not regional indicator sequences — most flags — are handled (these are somewhat correlated with ZWJ being handled, but are not themselves ZWJ based)


And that's _just_ for emoji. This doesn't even get into how bad this is for other writing systems.

I'd be more open to this if there were some sort of standardized "bad" behavior for terminals which don't wish to handle this, but there isn't.

**Comment by Manishearth** [comment]
I think it _may_ be okay for this crate to provide a `wcwidth()` implementation but AIUI `wcwidth()` is itself dependent on `LC_CTYPE`.

The rather simple `General_Category` + `East_Asian_Width` impl described in [the docs of python's wcwidth](https://wcwidth.readthedocs.io/en/stable/specs.html) seems somewhat decent, but again I don't know if this matches actual implementations. I think there are some parts of those docs that diverge from the behavior I have seen.

**Comment by joshtriplett** [comment]
> I think it may be okay for this crate to provide a wcwidth() implementation but AIUI wcwidth() is itself dependent on LC_CTYPE.

Beyond just whether LC_CTYPE is a UTF-8 locale? Because at this point I think it's safe to assume cases not using such a locale aren't worth supporting.
